USE [master]
GO

/****** Object:  Database [BookManagement]    Script Date: 26-03-2021 20:34:46 ******/
CREATE DATABASE [BookManagement]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Books', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\Books.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Books_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\Books_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [BookManagement].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [BookManagement] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [BookManagement] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [BookManagement] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [BookManagement] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [BookManagement] SET ARITHABORT OFF 
GO

ALTER DATABASE [BookManagement] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [BookManagement] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [BookManagement] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [BookManagement] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [BookManagement] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [BookManagement] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [BookManagement] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [BookManagement] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [BookManagement] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [BookManagement] SET  DISABLE_BROKER 
GO

ALTER DATABASE [BookManagement] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [BookManagement] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [BookManagement] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [BookManagement] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [BookManagement] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [BookManagement] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [BookManagement] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [BookManagement] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [BookManagement] SET  MULTI_USER 
GO

ALTER DATABASE [BookManagement] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [BookManagement] SET DB_CHAINING OFF 
GO

ALTER DATABASE [BookManagement] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [BookManagement] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [BookManagement] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [BookManagement] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [BookManagement] SET QUERY_STORE = OFF
GO

ALTER DATABASE [BookManagement] SET  READ_WRITE 
GO


